name: Triage Bot
on:
  issues:
    types:
      - opened

jobs:
  triage-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: 'body'
          parameters: '[{"keywords": ["frog"], "labels": ["frog-label"], "assignees": []}, {"keywords": ["toad"], "labels": ["toad-label"], "assignees": []}, {"keywords": ["fish"], "labels": ["fish-label"], "assignees": []}, {"keywords": ["mouse"],"labels": ["mouse-label"],"assignees": []}]'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
